backend:
  name: github
  repo: gfrancis13/portfolio-v4
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: '/blog'
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { label: 'Description', name: 'description', widget: 'text' }
      - {
          label: 'Featured Image',
          name: 'thumbnail',
          widget: 'image',
          required: false,
        }
      - { name: body, label: Body, widget: markdown }
  - name: projects
    label: Projects
    folder: '/projects'
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: 'link', label: 'Link', widget: 'string' }
      - { name: 'github', label: 'Github', widget: 'string' }
      - {
          label: 'Featured Image',
          name: 'thumbnail',
          widget: 'image',
          required: false,
        }
      - { name: body, label: Body, widget: markdown }
